name: Doxygen deployment

on:
  push:
    branches: [ "master" ]

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Installing Doxygen
      run: |
        sudo apt-get update && \
        sudo apt-get install -y --no-install-recommends doxygen

    - name: Building Doxygen
      run: doxygen docs/doxygen.cfg

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: doxygen-site
        path: ./build
