name: Doxygen deployment

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  doxygen:
    environment:
      name: doxygen-site
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Installing Doxygen
      run: |
        sudo apt-get update && \
        sudo apt-get install -y --no-install-recommends doxygen graphviz
    - name: Building Doxygen
      run: doxygen docs/doxygen.cfg
    - name: Upload Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: doxygen-site
        path: __html/doxygen
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
